name: Checkout Vial

inputs:
  path:
    default: '__vial__'
    type: string
    required: false
    
runs:
  using: 'composite'
  steps:
    - name: Checkout vial
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.path }}
        repository: vial-kb/vial-qmk
        submodules: recursive
        ref: ${{ inputs.version }}
        
    - name: Setup Vial
      shell: bash
      run: |
        cd ${{ inputs.path }}
        make git-submodule
        cd ..
