version: "3.8"

services:
  workspace:
    container_name: "qmk-vial-builder-workspace"
    image: ghcr.io/qmk/qmk_cli:latest
    volumes:
      - ..:/workspace:cached
      - fwbuild-bashhistory:/commandhistory
volumes:
  fwbuild-bashhistory:
