version: "3.8"

services:
  workspace:
    container_name: "qmk-vial-builder-workspace"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - fwbuild-bashhistory:/commandhistory
volumes:
  fwbuild-bashhistory:
