name: Build a vial firmware

on:
  workflow_call:
    inputs:
      keyboard:
        type: string
        required: true
      keymap:
        type: string  
        required: true
        
jobs:
  build:
    name: Build a Vial firmware ${{ inputs.keyboard }}:${{ inputs.keymap }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Checkout vial
        uses: ./.github/actions/checkout-vial
      
      # 対象の keyboard のフォルダを vial にコピーする
      - name: Install a link to own source
        run: ln -s $(pwd)/${{ inputs.keyboard }} __vial__/keyboards/gku34
        
      - name: Compile and link
        run: make ${{ inputs.keyboard }}:${{ inputs.keymap }}

      - name: Archive built firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.keyboard }}-${{ inputs.keymap }}-vial-firmware
          path: __vial__/*.uf2
