name: Build a QMK firmware

on: 
  workflow_call:
    inputs:
      qmk_version:
        default: '0.21.5'
        type: string
        required: false
      keyboard:
        type: string
        required: true
      keymap:
        type: string  
        required: true
        
jobs:
  build:
    name: Build a QMK firmware ${{ inputs.keyboard }}:${{ inputs.keymap }}
    
    # runner を指定
    runs-on: ubuntu-latest
    # ステップを実行するコンテナイメージ
    container:
      image: ghcr.io/qmk/qmk_cli:latest
      
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Checkout qmk_firmware
        uses: ./.github/actions/checkout-qmk_firmware
        
      # 対象の keyboard のフォルダを qmk_firmware にコピーする
      - name: Install a link to own source
        run: ln -s $(pwd)/keyboards/${{ inputs.keyboard }} __qmk__/keyboards/${{ inputs.keyboard }}
        
      - name: Compile and link
        run: qmk compile -j 4 -kb ${{ inputs.keyboard }} -km ${{ inputs.keymap }}
        
      - name: Archive built firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.keyboard }}-${{ inputs.keymap }}-firmware
          path: __qmk__/*.uf2
