name: Build a vial by user

on:
  workflow_dispatch:
    inputs:
      keybaord:
        required: true
        type: choice
        options:
          - gku34

jobs:
  build:
    uses: ./.github/workflows/build-vial.yml
    with:
      keyboard: ${{ inputs.keybaord }}
    