name: Build a vial firmware

on:
  workflow_call:
    inputs:
      keyboard:
        type: string
        required: true
        
jobs:
  build:
    name: Build a Vial firmware ${{ inputs.keyboard }}
    
    runs-on: ubuntu-latest
    # ステップを実行するコンテナイメージ
    container:
      image: ghcr.io/qmk/qmk_cli:latest
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Checkout vial
        uses: ./.github/actions/checkout-vial
      
      # 対象の keyboard のフォルダを vial にコピーする
      - name: Install a link to own source
        run: ln -s $(pwd)/${{ inputs.keyboard }} __vial__/keyboards/gku34
        
      - name: Compile and link
        run: |
          cd __vial__
          make ${{ inputs.keyboard }}:vial

      - name: Archive built firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.keyboard }}-vial-firmware
          path: __vial__/*.uf2
